meta:
  dockerhub:
    email:    (( vault "secret/dockerhub:email" ))
    username: (( vault "secret/dockerhub:username" ))
    password: (( vault "secret/dockerhub:password" ))
    repository: starkandwaynebot/slack-notification-resource


jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: git
    trigger: true
  - put: edge-image
    params:
      build: git
#   on_failure:
#     put: notify
#       params:
#         text: "slack-notification-resource docker image failed to build"

#- name: rc
#  public: true
#  plan:
#  - aggregate:
#    - get: spruce
#      resource: git-spruce
#      passed: [testflight]
#      trigger: true
#    - get: version
#      trigger: false
#      params: {pre: rc}
#  - put: version
#    params: {file: version/number}

- name: minor
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: major}
  - put: version
    params: {file: version/number}

- name: promote
  public: true
  serial: true
  plan:
  - aggregate:
    - get: version
    - get: edge-image
    - get: git
  - put: latest-image
  - put: latest-image
    params:
      tag: version/number
      tag_prefix: v
  - aggregate:
    - put: version
      params: 
        bump: patch
    - put: github-final-release
      params:
        name: create-final-release/spruce/releases/name
        tag: create-final-release/spruce/releases/tag
        body: create-final-release/spruce/releases/notes.md
        globs:
        - create-final-release/spruce/releases/spruce-*

resources:
- name: git
  type: git
  source:
    #    uri: https://github.com/cloudfoundry-community/slack-notification-resource.git
    uri: https://github.com/dennisjbell/slack-notification-resource.git
    branch: master
    private_key: (( vault "secret/pipelines/slack-notification-resource/github/dennisjbell:private" ))

- name: edge-image
  type: docker-image
  source:
    .: (( inject meta.dockerhub ))
    tag: edge

- name: latest-image
  type: docker-image
  source:
    .: (( inject meta.dockerhub ))
    tag: latest

- name: version
  type: semver
  source :
    driver: s3
    bucket: slack-notification-resource-pipeline
    key: version
    access_key_id: (( vault "secret/aws/cfcommunity:access" ))
    secret_access_key: (( vault "secret/aws/cfcommunity:secret" ))
    initial_version: 0.0.1

#- name: notify
#  type: slack-notification


- name: github-final-release
  type: github-release
  source:
    user: dennisjbell
    #user: cloudfoundry-community
    repository: slack-notification-resource
    access_token: (( vault "secret/pipelines/slack-notification-resource/github:token" ))
